### ISSUE TITLE
It is not clear what this project actually does

### ISSUE THREAD

**Issue by penguineer** [quintessence/slack-icons#11]
As somebody who stumbles upon this project without prior knowledge I cannot find out what the purpose or goal of this project is.

A short sentence "This project aims at …" or something similar at the beginning of the README would be nice.

(I would hand in a PR, but I don't know what to write.)

**Comment by quintessence** [comment]
It is a collection of emojis. People can upload them to Slack, Discord, Mastodon, etc.

**Comment by penguineer** [comment]
Thank you for the clarification! :)
